<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\FormField;

class FormFieldSeeder extends Seeder
{
    /**
     * Seed field-field default yang sudah ada di form pendaftaran pemagang.
     * Urutan mengikuti tampilan form saat ini.
     */
    public function run(): void
    {
        $fields = [
            // ===== FORM UTAMA =====
            [
                'field_key'   => 'fullname',
                'field_type'  => 'text',
                'label'       => 'Nama Lengkap',
                'placeholder' => 'Muhammad Sumbul',
                'is_required' => true,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 10,
                'column_span' => 1,
            ],
            [
                'field_key'   => 'student_id',
                'field_type'  => 'text',
                'label'       => 'NIM / NPM',
                'placeholder' => '21552011045',
                'helper_text' => 'Contoh: 21552011045',
                'is_required' => true,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 20,
                'column_span' => 2,
            ],
            [
                'field_key'   => 'born_date',
                'field_type'  => 'date',
                'label'       => 'Tanggal Lahir',
                'is_required' => true,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 30,
                'column_span' => 2,
            ],
            [
                'field_key'   => 'institution_name',
                'field_type'  => 'text',
                'label'       => 'Universitas',
                'placeholder' => 'Telkom University',
                'is_required' => true,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 40,
                'column_span' => 2,
            ],
            [
                'field_key'   => 'study_program',
                'field_type'  => 'text',
                'label'       => 'Program Studi',
                'placeholder' => 'Rekayasa Perangkat Lunak',
                'is_required' => true,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 50,
                'column_span' => 2,
            ],
            [
                'field_key'   => 'faculty',
                'field_type'  => 'text',
                'label'       => 'Fakultas',
                'placeholder' => 'Ilmu Komputer',
                'is_required' => true,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 60,
                'column_span' => 2,
            ],
            [
                'field_key'   => 'current_city',
                'field_type'  => 'text',
                'label'       => 'Kota Domisili',
                'placeholder' => 'Yogyakarta',
                'is_required' => true,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 70,
                'column_span' => 2,
            ],
            [
                'field_key'   => 'email',
                'field_type'  => 'email',
                'label'       => 'Email',
                'placeholder' => 'kamu@email.com',
                'is_required' => true,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 80,
                'column_span' => 2,
            ],
            [
                'field_key'   => 'phone_number',
                'field_type'  => 'tel',
                'label'       => 'No. HP (WhatsApp)',
                'placeholder' => '08xxxxxxxxxx',
                'helper_text' => 'Hanya angka, contoh: 08123456789',
                'is_required' => true,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 90,
                'column_span' => 2,
            ],
            [
                'field_key'   => 'gender',
                'field_type'  => 'radio',
                'label'       => 'Jenis Kelamin',
                'options'     => [
                    ['value' => 'Laki-laki',  'label' => 'Laki-laki'],
                    ['value' => 'Perempuan',  'label' => 'Perempuan'],
                ],
                'is_required' => true,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 100,
                'column_span' => 1,
            ],
            [
                'field_key'   => 'internship_interest',
                'field_type'  => 'select',
                'label'       => 'Divisi Diminati',
                'placeholder' => '-- Pilih Divisi --',
                'is_required' => true,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 110,
                'column_span' => 1,
                'helper_text' => 'Diisi otomatis dari daftar divisi aktif',
            ],
            [
                'field_key'   => 'start_date',
                'field_type'  => 'date',
                'label'       => 'Tanggal Mulai',
                'is_required' => false,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 120,
                'column_span' => 2,
            ],
            [
                'field_key'   => 'end_date',
                'field_type'  => 'date',
                'label'       => 'Tanggal Selesai',
                'is_required' => false,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 130,
                'column_span' => 2,
            ],
            [
                'field_key'   => 'internship_type',
                'field_type'  => 'select',
                'label'       => 'Jenis Magang',
                'placeholder' => '-- Pilih --',
                'options'     => [
                    [
                        'value'       => 'Magang Mitra',
                        'label'       => 'Magang Mitra',
                        'description' => 'Magang melalui kerja sama kampus dengan perusahaan berdasarkan rekomendasi atau penempatan dari kampus.',
                    ],
                    [
                        'value'       => 'Magang Reguler',
                        'label'       => 'Magang Reguler',
                        'description' => 'Magang dari kampus yang dipilih dan diajukan sendiri oleh pemagang, serta digunakan untuk pemenuhan atau penilaian akademik.',
                    ],
                    [
                        'value'       => 'Magang Inisiatif Pribadi',
                        'label'       => 'Magang Inisiatif Pribadi',
                        'description' => 'Magang atas inisiatif sendiri tanpa rekomendasi atau kerja sama khusus dari kampus.',
                    ],
                ],
                'is_required' => true,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 140,
                'column_span' => 2,
            ],
            [
                'field_key'   => 'internship_arrangement',
                'field_type'  => 'select',
                'label'       => 'Sistem Magang',
                'placeholder' => '-- Pilih --',
                'options'     => [
                    ['value' => 'Onsite', 'label' => 'Onsite (WFO)'],
                ],
                'is_required' => true,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 150,
                'column_span' => 2,
            ],
            [
                'field_key'   => 'internship_reason',
                'field_type'  => 'textarea',
                'label'       => 'Alasan Ingin Magang di Sini',
                'placeholder' => 'Tuliskan alasan Anda...',
                'is_required' => true,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 160,
                'column_span' => 1,
            ],
            [
                'field_key'   => 'current_status',
                'field_type'  => 'select',
                'label'       => 'Status Saat Ini',
                'placeholder' => '-- Pilih --',
                'options'     => [
                    ['value' => 'Mahasiswa/Pelajar', 'label' => 'Masih Kuliah/Sekolah'],
                    ['value' => 'Tidak Bekerja',     'label' => 'Lulus & Belum Bekerja'],
                    ['value' => 'Karyawan',          'label' => 'Lulus & Sudah Bekerja'],
                ],
                'is_required' => true,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 170,
                'column_span' => 1,
            ],
            [
                'field_key'   => 'english_book_ability',
                'field_type'  => 'select',
                'label'       => 'Kemampuan Membaca Buku Bahasa Inggris',
                'placeholder' => '-- Pilih --',
                'options'     => [
                    ['value' => 'Saya bisa',   'label' => 'Saya bisa'],
                    ['value' => 'Kurang bisa', 'label' => 'Kurang bisa'],
                    ['value' => 'Tidak bisa',  'label' => 'Tidak bisa'],
                ],
                'is_required' => true,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 180,
                'column_span' => 1,
            ],
            [
                'field_key'   => 'design_software',
                'field_type'  => 'text',
                'label'       => 'Software Desain',
                'placeholder' => 'Figma, Photoshop',
                'is_required' => false,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 190,
                'column_span' => 2,
            ],
            [
                'field_key'   => 'programming_languages',
                'field_type'  => 'text',
                'label'       => 'Bahasa Pemrograman',
                'placeholder' => 'PHP, JS',
                'is_required' => false,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 200,
                'column_span' => 2,
            ],
            [
                'field_key'   => 'video_software',
                'field_type'  => 'text',
                'label'       => 'Materi Digital Marketing',
                'placeholder' => 'SEO, Ads',
                'is_required' => false,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 210,
                'column_span' => 2,
            ],
            [
                'field_key'   => 'cv_ktp_portofolio_pdf',
                'field_type'  => 'file',
                'label'       => 'Surat Pengantar (PDF)',
                'helper_text' => 'Maks. 2MB, format PDF saja',
                'is_required' => true,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 220,
                'column_span' => 2,
            ],
            [
                'field_key'   => 'portofolio_visual',
                'field_type'  => 'file',
                'label'       => 'CV / Portfolio (PDF)',
                'helper_text' => 'Maks. 2MB, format PDF saja',
                'is_required' => true,
                'is_system'   => true,
                'group_name'  => null,
                'sort_order'  => 230,
                'column_span' => 2,
            ],

            // ===== INFORMASI TAMBAHAN =====
            [
                'field_key'   => 'family_status',
                'field_type'  => 'select',
                'label'       => 'Status Keluarga',
                'options'     => [
                    ['value' => 'Tidak', 'label' => 'Belum Menikah'],
                    ['value' => 'Ya',    'label' => 'Sudah Menikah'],
                ],
                'is_required' => false,
                'is_system'   => true,
                'group_name'  => 'informasi_tambahan',
                'sort_order'  => 10,
                'column_span' => 1,
            ],
            [
                'field_key'   => 'boarding_info',
                'field_type'  => 'select',
                'label'       => 'Butuh Informasi Kost?',
                'options'     => [
                    ['value' => 'Tidak', 'label' => 'Tidak'],
                    ['value' => 'Ya',    'label' => 'Ya'],
                ],
                'is_required' => false,
                'is_system'   => true,
                'group_name'  => 'informasi_tambahan',
                'sort_order'  => 20,
                'column_span' => 1,
            ],
            [
                'field_key'   => 'parent_wa_contact',
                'field_type'  => 'tel',
                'label'       => 'No. WA Wali / Orang Tua',
                'placeholder' => '08xxxxxxxxxx',
                'helper_text' => 'Hanya angka, opsional',
                'is_required' => false,
                'is_system'   => true,
                'group_name'  => 'informasi_tambahan',
                'sort_order'  => 30,
                'column_span' => 1,
            ],
            [
                'field_key'   => 'social_media_instagram',
                'field_type'  => 'text',
                'label'       => 'Instagram',
                'placeholder' => 'username_kamu',
                'is_required' => false,
                'is_system'   => true,
                'group_name'  => 'informasi_tambahan',
                'sort_order'  => 40,
                'column_span' => 1,
            ],
            [
                'field_key'   => 'internship_info_sources',
                'field_type'  => 'checkbox',
                'label'       => 'Tahu Info Magang Dari',
                'options'     => [
                    ['value' => 'Instagram',      'label' => 'Instagram'],
                    ['value' => 'TikTok',         'label' => 'TikTok'],
                    ['value' => 'LinkedIn',       'label' => 'LinkedIn'],
                    ['value' => 'Referral Teman', 'label' => 'Referral Teman'],
                    ['value' => 'Website',        'label' => 'Website'],
                    ['value' => 'Campus',         'label' => 'Kampus/Universitas'],
                    ['value' => 'Lainnya',        'label' => 'Lainnya'],
                ],
                'is_required' => false,
                'is_system'   => true,
                'group_name'  => 'informasi_tambahan',
                'sort_order'  => 50,
                'column_span' => 1,
            ],
        ];

        foreach ($fields as $field) {
            FormField::updateOrCreate(
                ['field_key' => $field['field_key']],
                $field
            );
        }
    }
}
